export const BUSINESS_CODE = {
  SUCCESS: 0,
  BAD_REQUEST: 400,
  SERVER_ERROR: 500,

  AUTH_UNAUTHENTICATED: 11000,
  AUTH_USER_NOT_FOUND: 11001,
  AUTH_TOKEN_MISSING: 11002,
  AUTH_ACCESS_TOKEN_INVALID: 11003,
  AUTH_ACCESS_TOKEN_EXPIRED: 11004,
  AUTH_REFRESH_TOKEN_INVALID: 11005,
  AUTH_SESSION_EXPIRED: 11006,
  AUTH_USER_STATUS_ABNORMAL: 11007,
  AUTH_ADMIN_REQUIRED: 11008,
  AUTH_LOGIN_FAILED: 11100,

  USER_NOT_FOUND: 12000,
  USERNAME_EXISTS: 12001,
  USER_PROFILE_NOT_FOUND: 12009,
  USER_PROFILE_UPDATE_FAILED: 12010,
  USER_IMAGE_EMPTY: 12900,
  USER_IMAGE_TOO_LARGE: 12901,
  USER_IMAGE_UNSUPPORTED_TYPE: 12902,
  USER_IMAGE_UPLOAD_FAILED: 12903,

  ARTICLE_NOT_FOUND: 13000,
  ARTICLE_STATUS_INVALID: 13003,
  ARTICLE_NOT_PUBLIC: 13004,
  ARTICLE_HIDDEN: 13005,
  ARTICLE_DELETED: 13006,
  ARTICLE_AUTHOR_REQUIRED: 13007,

  COMMENT_NOT_FOUND: 14100,
  COMMENT_HIDDEN: 14101,
  COMMENT_DELETED: 14102,
  COMMENT_AUTHOR_REQUIRED: 14103,
} as const;

export type BusinessCode = (typeof BUSINESS_CODE)[keyof typeof BUSINESS_CODE];

const BUSINESS_CODE_MESSAGE: Partial<Record<BusinessCode, string>> = {
  [BUSINESS_CODE.BAD_REQUEST]: '请求参数有误，请检查后重试。',
  [BUSINESS_CODE.SERVER_ERROR]: '服务器暂时开小差，请稍后再试。',

  [BUSINESS_CODE.AUTH_UNAUTHENTICATED]: '请先登录。',
  [BUSINESS_CODE.AUTH_USER_NOT_FOUND]: '登录用户不存在，请重新登录。',
  [BUSINESS_CODE.AUTH_TOKEN_MISSING]: '请先登录。',
  [BUSINESS_CODE.AUTH_ACCESS_TOKEN_INVALID]: '登录状态无效，请重新登录。',
  [BUSINESS_CODE.AUTH_ACCESS_TOKEN_EXPIRED]: '登录已过期，正在尝试刷新。',
  [BUSINESS_CODE.AUTH_REFRESH_TOKEN_INVALID]: '登录已失效，请重新登录。',
  [BUSINESS_CODE.AUTH_SESSION_EXPIRED]: '登录状态已失效，请重新登录。',
  [BUSINESS_CODE.AUTH_USER_STATUS_ABNORMAL]: '账号状态异常，暂时无法继续操作。',
  [BUSINESS_CODE.AUTH_ADMIN_REQUIRED]: '当前账号没有管理员权限。',
  [BUSINESS_CODE.AUTH_LOGIN_FAILED]: '用户名或密码错误。',

  [BUSINESS_CODE.USER_NOT_FOUND]: '用户不存在。',
  [BUSINESS_CODE.USERNAME_EXISTS]: '用户名已存在，请更换后重试。',
  [BUSINESS_CODE.USER_PROFILE_NOT_FOUND]: '用户资料不存在。',
  [BUSINESS_CODE.USER_PROFILE_UPDATE_FAILED]: '用户资料更新失败，请稍后再试。',
  [BUSINESS_CODE.USER_IMAGE_EMPTY]: '请选择要上传的图片。',
  [BUSINESS_CODE.USER_IMAGE_TOO_LARGE]: '图片不能超过 5MB，请压缩或更换图片。',
  [BUSINESS_CODE.USER_IMAGE_UNSUPPORTED_TYPE]: '请选择 png、jpg 或 webp 格式的图片。',
  [BUSINESS_CODE.USER_IMAGE_UPLOAD_FAILED]: '图片上传失败，请稍后再试。',

  [BUSINESS_CODE.ARTICLE_NOT_FOUND]: '文章不存在。',
  [BUSINESS_CODE.ARTICLE_STATUS_INVALID]: '文章状态暂不支持此操作。',
  [BUSINESS_CODE.ARTICLE_NOT_PUBLIC]: '文章未发布或不可公开访问。',
  [BUSINESS_CODE.ARTICLE_HIDDEN]: '文章已被屏蔽。',
  [BUSINESS_CODE.ARTICLE_DELETED]: '文章已被删除。',
  [BUSINESS_CODE.ARTICLE_AUTHOR_REQUIRED]: '只有文章作者可以执行此操作。',

  [BUSINESS_CODE.COMMENT_NOT_FOUND]: '评论不存在。',
  [BUSINESS_CODE.COMMENT_HIDDEN]: '评论已被屏蔽，暂不可访问。',
  [BUSINESS_CODE.COMMENT_DELETED]: '评论已被删除，请刷新列表。',
  [BUSINESS_CODE.COMMENT_AUTHOR_REQUIRED]: '只有评论作者可以删除评论。',
};

export function getBusinessCodeMessage(code: unknown): string | null {
  return typeof code === 'number' ? BUSINESS_CODE_MESSAGE[code as BusinessCode] ?? null : null;
}
